version: '2.0'
services:
  wps:
    image: birdhouse/pywps-gridengine-demo
    hostname: xenon-gridengine
    environment:
      HOSTNAME: xenon-gridengine
      HTTP_PORT: 5000
      OUTPUT_PORT: 5001
    ports:
      # wps port
      - "5000:5000"
      # nginx output port
      - "5001:5001"
  db:
    hostname: db
    image: postgres
    environment:
      POSTGRES_PASSWORD: testdb
    #  ports:
    #    - "5432:5432"
