version: '2.0'
services:
  wps:
    image: birdhouse/pywps-gridengine-demo
    hostname: localhost
    environment:
      HOSTNAME: localhost
      HTTP_PORT: 5000
      OUTPUT_PORT: 5001
    ports:
      # wps port
      - "5000:5000"
      # nginx output port
      - "5001:5001"
    volumes:
      - lib:/opt/birdhouse/var/lib
      - log:/opt/birdhouse/var/log
  gridengine:
    image: birdhouse/gridengine-wps
    hostname: gridengine
    environment:
      HOSTNAME: gridengine
    volumes:
      - lib:/opt/birdhouse/var/lib
      - log:/opt/birdhouse/var/log
  db:
    hostname: db
    image: postgres
    environment:
      POSTGRES_PASSWORD: testdb
    #  ports:
    #    - "5432:5432"

volumes:
  lib:
  log:
