version: '2.0'
services:
  wps:
    image: birdhouse/pywps-gridengine-demo
    hostname: wps
    environment:
      HOSTNAME: wps
      HTTP_PORT: 5000
      OUTPUT_PORT: 5001
    ports:
      # wps port
      - "5000:5000"
      # nginx output port
      - "5001:5001"
    volumes:
      - lib:/opt/birdhouse/var/lib
      - log:/opt/birdhouse/var/log
      - run:/opt/birdhouse/var/run
  gridengine:
    image: birdhouse/gridengine-wps
    hostname: gridengine
    environment:
      HOSTNAME: gridengine
    # ports:
    #   - "6444:6444"
    command: ["gridengine-master"]
  worker1:
    image: birdhouse/gridengine-wps
    hostname: worker1
    environment:
      HOSTNAME: worker1
    # ports:
    #   - "6445:6445"
    volumes:
      - lib:/opt/birdhouse/var/lib
      - log:/opt/birdhouse/var/log
    command: ["gridengine-exec"]
  db:
    hostname: db
    image: postgres
    environment:
      POSTGRES_PASSWORD: testdb
    #  ports:
    #    - "5432:5432"

volumes:
  lib:
  log:
  run:
